### ISSUE TITLE
Flickering popup window

### ISSUE THREAD

**Issue by MoAlyousef** [nsalguero/yabinero#1]
Hi

Nice game application. When trying it out I noticed some flickering in the popup windows. If you could try a DoubleWindow which provides double buffering:

```rust
fn popup_window(width: i32, height: i32, title: &str) -> Window {
    let window = DoubleWindow::new(0, 0, width, height, title);
    init_window(window, true)
}
```

**Comment by nsalguero** [comment]
Hi,

Thanks for your advice.  I will try ASAP.

Best regards,

Nico.

**Comment by nsalguero** [comment]
Hi,

Version 1.22.0 uses DoubleWindow.  Does it fix the issue?

Best regards,

Nico.

**Comment by MoAlyousef** [comment]
Hi
Yes it does. Thank you.
